# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, flake-inputs, ... }:

{
  imports = [ 
    flake-inputs.nixos-hardware.nixosModules.framework-13-7040-amd
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems = {
    "/boot" = { 
      device = "/dev/disk/by-uuid/4846-7136";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    "/" = { 
      device = "/dev/disk/by-uuid/de50c93c-1694-486b-a5f0-b01e39bb116d";
      fsType = "ext4";
    };
  };

  swapDevices = [ 
    { device = "/dev/disk/by-uuid/8b968203-fa95-49fd-a9bd-5b20a2562754"; } 
  ];

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    bluetooth.enable = true; # enables support for Bluetooth

    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
